name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build puppeteer
        run: npm run build
      - name: Publish puppeteer
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm config set registry 'https://registry.npmjs.org/'
          npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
          echo "Publishing puppeteer"
          npm publish
